runners:
 local-runner:
  image: work3-System-Product-Name:5000/ubuntu-generic
  
jobs:   
 build_run_sim:
  resource_spec: micro 
  runner: local-runner
  privileged: True
  steps:
   - run:
      name: Setup Environment
      command: |
       apt-get -y update
       apt-get -y install python3-pip
       pip3 install rshell
       apt-get -y install minicom
       pip3 install adafruit-ampy
   - run:
      name: Connect to Pico
      command: |
       ampy --port /dev/ttyACM0 run somefile.py
    
workflows:
 complete-build-test:
  jobs:
   - build_run_sim
