runners:
 local-runner:
  image: work3-System-Product-Name:5000/ubuntu-generic
  
jobs:   
 build_run_sim:
  resource_spec: micro 
  runner: local-runner
  privileged: True
  steps:
   - run:
      name: Setup Environment
      command: |
       apt-get -y update
       apt-get -y install python3-pip
       pip3 install rshell
       apt-get -y install minicom
   - run:
      name: Connect to Pico
      command: |
       rshell --buffer-size=512 -p /dev/ttyACM0 cp somefile.py /flash
       rshell --buffer-size=512 -p /dev/ttyACM0 shell ls
       rshell --buffer-size=512 -p /dev/ttyACM0 shell python somefile.py
    
workflows:
 complete-build-test:
  jobs:
   - build_run_sim
