runners:
 local-runner:
  image: work3-System-Product-Name:5000/ubuntu-generic
  
jobs:   
 build_run_sim:
  resource_spec: micro 
  runner: local-runner
  steps:
   - run:
      name: Setup Environment
      command: |
       apt-get -y update
       apt-get -y install python3-pip
       pip3 install rshell
       apt-get -y install minicom
   - run:
      name: Connect to Pico
      command: |
       ls -l /dev
       rshell --buffer-size=512 -p /dev/ttyACM0
    
workflows:
 complete-build-test:
  jobs:
   - build_run_sim
